### ISSUE TITLE
Create DB Schema

### ISSUE THREAD

**Issue by garora** [garora/blogit#4]
We need to create DB Schema, the idea is to make it as simpler as possible. DB Schema would contain:
1. `User` Table
2. `User_Role` Table
3. `Posts` Table
4. `Comments` Table
5. `Post_Type` Table - can contain types of posts
6. `Configuration` Table etc.

Above, is just idea of few tables, we need to think about all possible scenarios, but definitely we should make it simpler one.

As a naming convention, I suggest to use prefix-`bl` with table name so, user table would be named as `bl_user`

@Hassankashi - We will add more description, if require.

**Comment by garora** [comment]
@Hassankashi - you're working on initial part so, I'm assigning this task to you.

Please let me know if you would like me to create DB Schema.

Regards,
Gaurav Arora

**Comment by Hassankashi** [comment]
@garora 
I have added some code which create tables inside database and I have found out codes which generate automatically class at run time which is useful for users to add their own table structure with their specific fields and their data type by "CodeDOM".

Please get new repo and follow these instruction:
1. Go to AppStart -> BundleConfig -> comment script (because I am just working in back end now)
2. Go to SQL2008 -> create database with this name "blogit"
3. Run solution
4. You will have this address on your url: http://localhost:XXXX/BuildDB/index
   as you see please add BuildDB as controller and index
5. Go to your database and refresh it , see your tables.

B.R
Mahsa Hassankashi.

**Comment by garora** [comment]
@Hassankashi - Its awesome! I am going to give it a try and will provide my feedback.

**Comment by garora** [comment]
@Hassankashi - I got the opportunity to see the thins. It is awesome. Just few tweaks
- added some files in `Utility project`
- I believe we need to make our `nhibernate configuration` in such a way so version of `MSSQL server` (onwards 2008) should be get supported
- We need to add Inversion of Control - as you are at the initial stage, so, please let me know what `IOC framework` you would like to add I am fine with any one but preferably `simpleinjection` or `Ninject`
- Once you will done with initial things, I will start building one Setup Tool which will create/setup new sites initially.

I am really appreciate your way, please let me know which architecture your are going to follow.

Thanks & Regards,
Gaurav Arora

**Comment by garora** [comment]
@Hassankashi - I just noticed we are already added `NinJect`. Also, I checked-in `Bundleconfig` with commented code - FYI

**Comment by Hassankashi** [comment]
Dear @garora I added EncryptionByAESController to the web project . I think it should be replaced to your utilities . I am finishing generated db by user . I was writing my tutorial . I wanna introduce our Github url after my changing , are you agree or is it too soon?
Best Regards
Mahsa

**Comment by garora** [comment]
@Hassankashi - thats awesome, I will take a look.

**Comment by garora** [comment]
@Hassankashi - Closing this issue as, you have already completed DB Schema tasks.
